---
global:
  log_level: debug
  check_events: true
  events:
    - BEFORE_EACH
    - AROUND_ALL
    - AROUND_EACH

plugins:
  - module: TestRunner::Plugin::SetupFixture #=> autoloading TestRunner::Plugin::SetupFixture, "test_runner/plugin/setup_fixture"
  - module: +TestTimer  # same means of TestRunner::Plugin::TestTimer #=> autoloading TestRunner::Plugin::TestTimer, "test_runner/plugin/test_timer"
  - module: +TestInfo
    config:
      template: start test %s
  - module: +TestInfo
    config:
      template: you can also ouput other info for %s

